# Configuration for Pyntel4004-cli.

title = "Configuration file for double_4bit.asm"

[asm]
input = "examples/double_4bit.asm"
output = "examples/double_4bit"
type = ["BIN", "H"]
exec = true
monitor = true
quiet = true

[dis]
object = "examples/double_4bit.obj"
inst = 6
labels = true

[exe]
object = "examples/double_4bit.obj"
quiet = true
